{{/*
Copyright (c) 2026 middleware-charts contributors.
SPDX-License-Identifier: Apache-2.0
*/}}

{{/* vim: set filetype=mustache: */}}

{{/*
Create the chart-managed credentials Secret unless an existing Secret is used.
*/}}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ include "postgresql.auth.usernameKey" . }}: {{ .Values.auth.username | quote }}
  {{ include "postgresql.auth.passwordKey" . }}: {{ .Values.auth.password | quote }}
  {{ include "postgresql.auth.databaseKey" . }}: {{ .Values.auth.database | quote }}
{{- end }}
