apiVersion: v2
name: postgresql
description: A maintainable single-instance PostgreSQL Helm chart using the PostgreSQL-compatible postgres-stack image
type: application
version: 0.1.2
appVersion: "18.6"
annotations:
  artifacthub.io/alternativeName: postgres
  artifacthub.io/category: database
  artifacthub.io/changes: |
    - kind: changed
      description: Use docker.io/buall/postgres-stack:18.6 as the default runtime image.
home: https://www.postgresql.org/
sources:
  - https://github.com/buall/buall-charts
  - https://github.com/postgres/postgres
keywords:
  - database
  - postgres
  - postgresql
maintainers:
  - name: middleware-charts
